### PR TITLE
Update Banner Text, Buttons, Logo, and Links

### PR DESCRIPTION
**Pull request by Kola92**
### Changes Overview
This pull request includes several updates to the banner to improve user experience and responsiveness.

1. **Text Change**
   - Updated the banner text from "Gain exposure to a variety of assets with up to 50x leverage and deep liquidity" to "Start Trading Perpetual Futures Now".

2. **Button Updates**
   - Modified buttons to wrap icons and text.
   - Ensured buttons have a fluid width to enhance responsiveness across different devices.

3. **Logo Replacement**
   - Replaced the current Kwenta logo with the new SVG provided.

4. **Link Removal**
   - Removed the Copin link and its associated text button from the banner.

### Testing
- Verified the new text displays correctly on the banner.
- Ensured the buttons are responsive and display icons and text properly across different screen sizes.
- Confirmed the new Kwenta logo renders correctly.
- Checked that the Copin link and button are no longer present.

### CODE REVIEW

**Review by jmzwar — CHANGES_REQUESTED** [review]
Hi - I don't think the package-lock is necessary. Please only use yarn.

**Comment by Kola92** [comment]
The package-lock file came along as a result of using npm to install all the package dependencies for the app, so should I just go ahead and delete the package-lock file

**Comment by jmzwar** [comment]
@Kola92 You can remove the yarn lock also

**Comment by Kola92** [comment]
The yarn.lock file has been removed

**Comment by jmzwar** [comment]
@Kola92 I meant the changes - we need to keep yarn.lock, there just shouldn't be any changes to it because no dependencies have changed.

**Comment by Kola92** [comment]
@jmzwar I don't get you, are you saying I should keep the yarn.lock but no changes should occur in it

**Comment by jmzwar** [comment]
> @jmzwar I don't get you, are you saying I should keep the yarn.lock but no changes should occur in it

That is right. The file stays, but there should be no commited changes to it in this pr, as no dependencies have changed.

**Pull request closed without merging**
